- name: Creating Directory
  file:
    path: /home/EarlV/docker_config
    state: directory

- name: Copy Dockerfile
  copy:
    src: Dockerfile
    dest: /home/EarlV/docker_config
    owner: EarlV
    group: EarlV

- name: Creating Volume
  file:
    path: /home/EarlV/pages
    state: directory

- name: Build Image
  community.docker.docker_image:
    name: lamp-EarlV
    tag: 1.0
    build:
      path: /home/EarlV/docker_config
    source: build

- name: Deploy Container
  community.docker.docker_container:
    name: lamp-EarlV
    image: lamp-EarlV:1.0
    state: started
    exposed_ports:
      - "80"
    ports:
      - "8080:80"
    volumes:
      - /home/EarlV/pages:/var/www/html

- block:
  - name: Verify if lamp-EarlV container is running
    shell: docker ps
    register: container_status

  - debug:
      msg="{{ container_status }}"
